spring:
  profiles:
    active: prod
    include: common

---
spring:
  config:
    activate:
      on-profile: prod

  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://jjaplix-app-backend-database.cnu55kzgf7wv.ap-northeast-2.rds.amazonaws.com:3306
    username: kansg
    password: !Q2w3e$R5