spring:
  profiles:
    active: dev

server:
  port: 8080
#  shutdown: graceful

common:
  aesc_key: C&F)J@NcRfUjXn2r

# mybatis
mybatis:
  type-aliases-package: co.dearu.api.message.repository
  mapper-locations: mybatis/mapper/**/*.xml

# log path -------------------------------------------------------------------------------------------------------------------------------------------------
logging:
  file:
    path: /dearu/logs
---
#■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■ Recap ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■
############################################################################################################################################################
## properties - DEV
############################################################################################################################################################
spring:
  config:
    activate:
      on-profile: dev
  # mysql datasource-----------------------------------------------------------------------------------------------------------------------------------------
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/recap
    username: root
    password: qwer1234
---
############################################################################################################################################################
## properties - live
############################################################################################################################################################
spring:
  config:
    activate:
      on-profile: live
  # mysql datasource-----------------------------------------------------------------------------------------------------------------------------------------
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://jjaplix-app-backend-database.cnu55kzgf7wv.ap-northeast-2.rds.amazonaws.com:3306
    username: kansg
    password: '!Q2w3e$R5'