spring:
  profiles:
    active: dev

server:
  port: 8080
#  shutdown: graceful

common:
  aesc_key: C&F)J@NcRfUjXn2r

# mybatis
mybatis:
  type-aliases-package: co.dearu.api.message.repository
  mapper-locations: mybatis/mapper/**/*.xml

# log path -------------------------------------------------------------------------------------------------------------------------------------------------
logging:
  file:
    path: /dearu/logs
---
#■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■ Recap ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■
############################################################################################################################################################
## properties - DEV
############################################################################################################################################################
spring:
  config:
    activate:
      on-profile: dev
  # mysql datasource-----------------------------------------------------------------------------------------------------------------------------------------
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbc-url: jdbc:mysql://175.116.50.125:3306/recap?useSSL=false
    username: kan
    password: kan100921
    max-lifetime: 30000
    connection-test-query: SELECT 1

---
############################################################################################################################################################
## properties - live
############################################################################################################################################################
spring:
  config:
    activate:
      on-profile: live
  # mysql datasource-----------------------------------------------------------------------------------------------------------------------------------------
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbc-url: jdbc:mysql://175.116.50.125:3306?useSSL=false
    username: kan
    password: kan100921
    max-lifetime: 30000
    connection-test-query: SELECT 1